spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: products-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm # nơi cấp phát
          jwk-set-uri: http://localhost:8080/realms/demo-realm/protocol/openid-connect/certs # lấy public key verify

server:
  port: 8181
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

