spring:
  application:
    name: product_service

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/product_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:250104}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
    show-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000

  logging:
    level:
      org.springframwork.cache: trace
      com.github.benmanes.caffeine: debug
      org.springframwork.data.redis: debug

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserialize: org.apache.kafka.common.serialization.StringDeserializer
      value-deserialize: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: 8081